version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ui.frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/tests/end-to-end"
    schedule:
      interval: "weekly"