name: Build checks

on:
  push:

  schedule:
    - cron: '0 3 * * 1,3,5'


env:
  AWS_REGION: "eu-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_CI_ROLE_TO_ASSUME }}
          role-session-name: BulmaPullRequestCheck
          aws-region: ${{ env.AWS_REGION }}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare Maven settings for Code Artifact
        run: |
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain websight --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text`
          mkdir -p ~/.m2/repository
          cp .github/settings.xml ~/.m2/settings.xml
          echo "CODEARTIFACT_AUTH_TOKEN=${CODEARTIFACT_AUTH_TOKEN}" >> $GITHUB_ENV
      - name: Build and test cypress with Maven
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        if: ${{ github.event_name == 'push' }}
        run: mvn --batch-mode --update-snapshots clean install -P e2e
      - name: Build and test visual with Maven
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        if: ${{ github.event_name == 'schedule' }}
        run: mvn --batch-mode --update-snapshots clean install -P visual-tests

